name: Run Tests

on:
  push:
#    branches: [ main ] # main 브랜치에 푸시될 때만 동작하도록 변경
    branches: [ "**" ] # 모든 브랜치에 대해 동작하도록 변경
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # [중요] npm 패키지 캐싱을 켜서 설치 단계 멈춤/지연 방지

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci # package.json에 정의한 스크립트 실행
        env:
          CI: true # 명시적으로 CI 환경임을 선언